<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Discord.Net.targets" />
  <Import Project="../../StyleAnalyzer.targets" />
  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
    <RootNamespace>Discord.AspNetCore</RootNamespace>
    <AssemblyName>Discord.Net.AspNetCore</AssemblyName>
    <Description>ASP.NET Core HTTP interactions integration for Discord.Net.</Description>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Discord.Net.Rest/Discord.Net.Rest.csproj" />
    <ProjectReference Include="../Discord.Net.Interactions/Discord.Net.Interactions.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
